---
- name: Check AS3 Status
  hosts: bigiq_cm
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: false

    - name: "ansible_password"
      prompt: "What is your password? "
      private: true

    - name: "f5_as3task_id"
      prompt: "What is the AS3 TASK ID to check? "
      private: false

  vars: # Create Auth JSON
    f5_login_json: "{{ lookup('template', './templates/f5_web_auth.j2') }}"

  tasks:

    - name: Login and Obtain Token
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/authn/login"
        method: POST
        body: "{{ f5_login_json }}"
        body_format: json
        status_code:
          - 200
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: f5_login_token_post

    - name: Test Service Get
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/info"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        status_code:
          - 200
          - 202
        timeout: 300
        validate_certs: false
      delegate_to: localhost
      register: f5_service
      tags:
        - service

    - name: "DISPLAY Result"
      ansible.builtin.debug:
        var: f5_service.json.results

    - name: "DISPLAY Errors if Any"
      ansible.builtin.debug:
        var: f5_service.json.errors


    - name: Check Status Get
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/task/{{ f5_as3task_id }}"
#        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/task/2f4cee61-436c-49c2-8666-68eaddcadad7"
#        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/task/18d6b49d-85d1-4e79-b4a4-e61b9a8d960e"
#        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare/cbb01421-81ce-48ed-b6b1-6f9d1bddca52"
#        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare/T1,T3?show=expanded"
#        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare?show=full"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        status_code:
          - 200
          - 202
          - 204
        timeout: 300
        validate_certs: false
      delegate_to: localhost
      register: f5_status
      tags:
        - status

    - name: "DISPLAY Result"
      ansible.builtin.debug:
        var: f5_status.json.results

    - name: "DISPLAY Errors if Any"
      ansible.builtin.debug:
        var: f5_status.json.errors
