---
- name: Extend Auth Token
  hosts: bigip
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "F5Host"
      prompt: "What Host Are you renewing?"
      private: no

    - name: "F5AuthToken"
      prompt: "What is your Current Token?"
      private: yes
 
  vars:
    - name: Create Auth JSON
      f5_login_json: "{{ lookup('template', './templates/f5_web_auth.j2') }}"

  tasks:

    - name: Patch Token for Timeout of 36000
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/authz/tokens/{{ F5AuthToken }}"
        method: PATCH
        headers:
          X-F5-Auth-Token: "{{ F5AuthToken }}"
        body: '[ { "timeout":"36000" } ]'
        body_format: json
        status_code: 
          - 200
        timeout: 300
        validate_certs: false
      delegate_to: localhost
      register: f5_login_token_patch
      
    - name: display f5_login_token_patch
      debug:
        msg: "{{ f5_login_token_patch }}"

