---
- name: TEST AS3
  hosts: bigiq_cm
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: no
 
    - name: "ansible_password"
      prompt: "What is your password? "
      private: yes

  tasks:

    - name: Test Get
      uri:
#        url: "https://172.26.63.112:443/mgmt/shared/appsvcs/info"
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/info"
        method: GET
        status_code: 200
        timeout: 300
## Note after BIG-IQ 5.1.0, BASIC AUTH is disabled by default and will just give a 401 error unless turned on
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      tags:
        - test-as3

    - name: PUSH AS3 new Config
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare"
# ASYNC is recomended but harder to test with
#        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare?async=true"
        method: POST
        body: "{{ lookup('file','./static_example/as3_bigiq.json') }}"
        status_code: 200
# IF ASYNC status code is 202
#        status_code: 202
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      tags:
        - new-config

    - name: PUSH AS3 blank aka remove Config
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare"
# ASYNC is recomended but harder to test with
#        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare?async=true"
        method: POST
        body: "{{ lookup('file','./static_example/as3_bigiq_erase.json') }}"
        status_code: 200
# IF ASYNC status code is 202
#        status_code: 202
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      tags:
        - remove-config