---
- name: TEST AS3
  hosts: bigip
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: no
 
    - name: "ansible_password"
      prompt: "What is your password? "
      private: yes

  tasks:

    - name: Test Get
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/info"
        method: GET
        status_code: 
          - 200
          - 202
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost

    - name: PUSH AS3
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('file','./static_example/as3.json') }}"
        status_code: 
          - 200
          - 202
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
