---
- name: TEST DO
  hosts: bigip
  connection: local
  gather_facts: false

  tasks:

    - name: Test Get
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/info"
        method: GET
        status_code: 202
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost

    - name: PUSH DO
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding"
        method: POST
        body: "{{ lookup('file','./static_example/do.json') }}"
        status_code: 202
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
