---
- name: Show BIG IP DO status
  hosts: bigiq_cm
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: no
 
    - name: "ansible_password"
      prompt: "What is your password? "
      private: yes

    - name: "last_task_check"
      prompt: "Do you want to skip showing last status? (anything but skip will shows last task status)"
      private: no
      default: "skip"

    - name: "task_id_a"
      prompt: "Optional: What is Task ID (A) Are you Checking (a null entry will skip)?"
      private: no
      default: "null"

    - name: "task_id_b"
      prompt: "Optional: What is Task ID (B) Are you Checking (a null entry will skip)"
      private: no
      default: "null"

  vars:
    - name: Create Auth JSON
      f5_login_json: "{{ lookup('template', './templates/f5_web_auth.j2') }}"

  tasks:

    - name: Login and Obtain Token
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/authn/login"
        method: POST
        body: "{{ f5_login_json }}"
        body_format: json
        status_code: 
          - 200
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: f5_login_token_post

    - name: Test Service Get
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/info"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        status_code: 
          - 200
          - 202
        timeout: 300
        validate_certs: false
      delegate_to: localhost
      tags:
        - service



    - name: Block for Last Task
      block:
      
      - name: Check Status - General/last
        uri:
          url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding"
          method: GET
          headers:
            X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
          status_code: 
            - 200
            - 202
          timeout: 300
          validate_certs: false
        delegate_to: localhost
        register: f5_status
        tags:
          - status
        ignore_errors: yes
  
      - name: "DISPLAY Result - General/last"
        debug:
          var: f5_status.json.result
  
      - name: "DISPLAY Errors if Any - General/last"
        debug:
          var: f5_status.json.errors
  
      when: not last_task_check == "skip"



    - name: Block for A
      block:
      
      - name: Check Status on ID {{ task_id_a }} 
        uri:
          url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/task/{{ task_id_a }}"
          method: GET
          headers:
            X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
          status_code: 
            - 200
            - 202
          timeout: 300
          validate_certs: false
        delegate_to: localhost
        register: f5_id_a_status
        tags:
          - status
        ignore_errors: yes
  
      - name: "DISPLAY TASK ID {{ task_id_a }} Result"
        debug:
          var: f5_id_a_status.json.result
  
      - name: "DISPLAY TASK ID {{ task_id_a }} Errors if Any"
        debug:
          var: f5_id_a_status.json.errors
      
      when: not task_id_a == "null"
        



    - name: Block for B
      block:
      
      - name: Check Status on ID {{ task_id_b }} 
        uri:
          url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/task/{{ task_id_b }}"
          method: GET
          headers:
            X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
          status_code: 
            - 200
            - 202
          timeout: 300
          validate_certs: false
        delegate_to: localhost
        register: f5_id_b_status
        tags:
          - status
        ignore_errors: yes
  
      - name: "DISPLAY TASK ID {{ task_id_b }} Result"
        debug:
          var: f5_id_b_status.json.result
  
      - name: "DISPLAY TASK ID {{ task_id_b }} Errors if Any"
        debug:
          var: f5_id_b_status.json.errors
        
      when: not task_id_b is match("null")
