---
- name: Show BIG IP DO status
  hosts: bigiq_cm
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: false

    - name: "ansible_password"
      prompt: "What is your password? "
      private: true

    - name: "last_task_check"
      prompt: "Do you want to skip showing last status? (anything but skip will shows last task status)"
      private: false
      default: "skip"

    - name: "task_id_a"
      prompt: "Optional: What is Task ID (A) Are you Checking (a null entry will skip)?"
      private: false
      default: "null"

    - name: "task_id_b"
      prompt: "Optional: What is Task ID (B) Are you Checking (a null entry will skip)"
      private: false
      default: "null"

  vars: # Import Auth JSON
    f5_login_json: "{{ lookup('template', './templates/f5_web_auth.j2') }}"

  tasks:

    - name: Login and Obtain Token
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/authn/login"
        method: POST
        body: "{{ f5_login_json }}"
        body_format: json
        status_code:
          - 200
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: f5_login_token_post

    - name: Test Service Get
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/info"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        status_code:
          - 200
          - 202
        timeout: 300
        validate_certs: false
      delegate_to: localhost
      tags:
        - service


    - name: Block for Last Task

      when: not last_task_check == "skip"

      block:

        - name: Check Status - General/last
          ansible.builtin.uri:
            url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding"
            method: GET
            headers:
              X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
            status_code:
              - 200
              - 202
            timeout: 300
            validate_certs: false
          delegate_to: localhost
          register: f5_status
          tags:
            - status
          ignore_errors: true

        - name: "DISPLAY Result - General/last"
          ansible.builtin.debug:
            var: f5_status.json.result

        - name: "DISPLAY Errors if Any - General/last"
          ansible.builtin.debug:
            var: f5_status.json.errors


    - name: Block for A

      when: not task_id_a == "null"

      block:

        - name: Check Status on ID {{ task_id_a }}
          ansible.builtin.uri:
            url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/task/{{ task_id_a }}"
            method: GET
            headers:
              X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
            status_code:
              - 200
              - 202
            timeout: 300
            validate_certs: false
          delegate_to: localhost
          register: f5_id_a_status
          tags:
            - status
          ignore_errors: true

        - name: "Result - DISPLAY TASK ID {{ task_id_a }}"
          ansible.builtin.debug:
            var: f5_id_a_status.json.result

        - name: "Errors if Any - DISPLAY TASK ID {{ task_id_a }}"
          ansible.builtin.debug:
            var: f5_id_a_status.json.errors


    - name: Block for B

      when: not task_id_b is match("null")

      block:

        - name: Check Status on ID {{ task_id_b }}
          ansible.builtin.uri:
            url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/task/{{ task_id_b }}"
            method: GET
            headers:
              X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
            status_code:
              - 200
              - 202
            timeout: 300
            validate_certs: false
          delegate_to: localhost
          register: f5_id_b_status
          tags:
            - status
          ignore_errors: true

        - name: "Result For - DISPLAY TASK ID {{ task_id_b }}"
          ansible.builtin.debug:
            var: f5_id_b_status.json.result

        - name: "Errors if Any - DISPLAY TASK ID {{ task_id_b }}"
          ansible.builtin.debug:
            var: f5_id_b_status.json.errors
