---
- name: DO Playbook - Generate DO files
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:

    - name: "bigip_user"
      prompt: "What is your username for BIG-IPs?"
      private: no

    - name: "bigip_password"
      prompt: "What is your password for BIG-IPs?"
      private: yes

  vars:

    - name: Import CSV File
      csvfile: "{{ lookup('file', './variables/device_variables.csv') }}"

  tasks:

    - name: Parse CSV To YAML
      template:
        src: "./templates/variable_template.j2"
        dest: "./output/config_variables.yml"
      run_once: true

    - include_vars: "./output/config_variables.yml"

    - name: BIG-IP Only create BIG-IP DO payload json based on Jinja2 Template and YAML from CSV
      template:
        src: "./templates/do_json_template.j2"
        dest: "./output/do.bigip.{{ item.unit.hostname }}.json"
      delegate_to: localhost
      with_items: "{{ devices }}"
      when: "'bigip' in item.unit.role"
      run_once: true

    - name: BIG-IP Only create BIG-IQ DO payload json based on nested Jinja2 Template and YAML from CSV
      template:
        src: "./templates/do_bigiq_json_template.j2"
        dest: "./output/do.bigiq.{{ item.unit.hostname }}.json"
      delegate_to: localhost
      with_items: "{{ devices }}"
      when: "'bigip' in item.unit.role"
      run_once: true
