---
# Playbook gathers show command output once devices are live and reachable
# Playbook starts by asking the username/password of user
# - List of devices are obtained from inventory files

- name: Pull Information, display
  hosts: all
#  connection: network_cli
  gather_facts: true
#  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: false

    - name: "ansible_password"
      prompt: "What is your password? "
      private: true

  tasks:

    - name: "DISPLAY ONLY HOST"
      ansible.builtin.debug:
        var: ansible_host

    - name: "DISPLAY ALL"
      ansible.builtin.debug:
        var: ansible_facts
