---
all:
  children:
    junos:
      children:
        qfx:
          children:
            bigiq_cm:
              hosts:
                lab-bigiq-cm1:
                  ansible_host: 10.0.55.6
            bigiq_dcd:
              # hosts:
                # lab-bigiq-dcd1:
                  # ansible_host: 10.50.55.5
            bigip:
              hosts:
                lab-bigip:
                  ansible_host: 110.0.55.7
                  ansible_hostname: lab-bigip
                lab-bigip2:
                  ansible_host: 10.0.55.8
                lab-bigip3:
                  ansible_host: 10.0.55.9
                  ansible_hostname: lab-bigip3
                  
    # local:
      # hosts:
        # localhost:
          # ansible_python_interpreter: /usr/local/bin/python3
