---
all:
  children:
    junos:
      children:
        qfx:
          children:
            bigiq_cm:
              hosts:
                 lab-bigiq-cm1:
                   ansible_host: 172.26.63.112
            bigiq_dcd:
              # hosts:
                # lab-bigiq-dcd1:
                  # ansible_host: 10.110.64.78
            bigip:
              hosts:
              #  lab-bigip:
              #    ansible_host: 172.26.63.113
              #    ansible_hostname: lab-bigip
                bigip1a:
                  ansible_host: 172.26.63.116
                bigip1b:
                  ansible_host: 172.26.63.117
    # local:
      # hosts:
        # localhost:
          # ansible_python_interpreter: /usr/local/bin/python3
