---
- name: BIG-IP AS3 Playbook CSV based Generate Push and Cleanup
  hosts: bigip
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: false

    - name: "ansible_password"
      prompt: "What is your password? "
      private: true

  vars: # Import CSV File
    csvfile: "{{ lookup('file', '../../variables/device_variables.csv') }}"

  tasks:

    - name: Python Script to create Vars list
      ansible.builtin.script:
        cmd: ../../scripts/vars_parse.py
        executable: /usr/bin/python3
      register: python_result
      tags:
        - test_files
        - test_files_and_cleanup

    - name: Include YAML style Vars from Python Output
      ansible.builtin.set_fact:
        devices: "{{ python_result.stdout }}"
      tags:
        - test_files
        - test_files_and_cleanup

    - name: Test Get AS3
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/info"
        method: GET
        status_code:
          - 200
          - 202
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost

    - name: BIG-IP Only create AS3 payload json based on Jinja2 Template and YAML from CSV # noqa: no-relative-paths
      ansible.builtin.template:
        src: "../../templates/as3_json_template.j2"
        dest: "../../output/as3.{{ item.unit.hostname }}.json"
        # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
        mode: "0644"
      delegate_to: localhost
      with_items: "{{ devices }}"
      when: "'bigip' in item.unit.role"
      tags:
        - test_files
        - test_files_and_cleanup

    - name: BIG-IP Only PUSH AS3 From Template
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('file', '../../output/as3.{{ inventory_hostname }}.json') }}"
        status_code:
          - 200
          - 202
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      when: "'bigip' in group_names"

#    - name: PUSH AS3 Static File
#      ansible.builtin.uri:
#        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare"
#        method: POST
#        body: "{{ lookup('file','as3.json') }}"
#        status_code: 200
#        timeout: 300
#        body_format: json
#        force_basic_auth: true
#        user: "{{ ansible_user }}"
#        password: "{{ ansible_password }}"
#        validate_certs: false
#      delegate_to: localhost
#      when: "'bigip' in group_names"
#
    - name: CLEANUP Remove AS3 JSON File(s) as3.[hostname].json on playbook completion
      ansible.builtin.file:
        path: ../../output/as3.{{ item.unit.hostname }}.json
        state: absent
      with_items: "{{ devices }}"
      tags:
        - test_files_and_cleanup
