---
- name: AS3 Playbook - Generate and Push DO via BIG-IQ
  hosts: bigiq_cm
  connection: local
  gather_facts: false

# Warning - as of 2023 F5 documentation states
# AS3 versions 3.42 and later are NOT compatible with BIG-IQ
# Be aware of what version AS3 is installed on BIG-IQ before attempting to use

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username for BIG-IQ?"
      private: false

    - name: "ansible_password"
      prompt: "What is your password for BIG-IQ?"
      private: true

  vars: # Create Auth JSON
    f5_login_json: "{{ lookup('template', '../../templates/f5_web_auth.j2') }}"

  tasks:

    - name: Login and Obtain Token
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/authn/login"
        method: POST
        body: "{{ f5_login_json }}"
        body_format: json
        status_code:
          - 200
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: f5_login_token_post
      when: "'bigiq_cm' in group_names"

    - name: Include YAML Vars
      ansible.builtin.include_vars: "../../output/config_variables.yml"

    - name: Test Service
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/info"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        status_code:
          - 200
          - 202
        timeout: 300
        validate_certs: false
      delegate_to: localhost
      when: "'bigiq_cm' in group_names"

    - name: BIG-IP Only PUSH AS3 From Template Generated File
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/declare?async=true"
        method: POST
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        body: "{{ lookup('file', '../../output/as3.{{ item.unit.hostname }}.json') }}"
        status_code:
          - 200
          - 202
        timeout: 300
        body_format: json
        validate_certs: false
      delegate_to: localhost
      register: f5_push
      when: ('bigiq_cm' in group_names) and ('bigip' in item.unit.role) and ('yes' in item.unit.push_as3)
      with_items: "{{ devices }}"

## Attempting to display task ID from API JSON response - not parsing well right now
#    - name: "DISPLAY more Errors if Any"
#      debug:
#        msg: " info {{item.json}}"
#      with_items: "{{f5_push.results}}"
#      ignore_errors: yes

#    - name: "DISPLAY Errors if Any"
#      debug:
#        var: f5_push.results[1-12].[item]
#      ignore_errors: yes

## Attempting to display task ID from API JSON response - if the number of loop item is known this works
#    - name: "DISPLAY Errors if Any"
#      debug:
#        var: f5_push.results[12].json
#      ignore_errors: yes
