---
- name: AS3 Playbook - Use CSV to Generate AS3 files (JSON Declarations)
  hosts: localhost
  connection: local
  gather_facts: false

# Warning - as of 2023 F5 documentation states
# AS3 versions 3.42 and later are NOT compatible with BIG-IQ
# Be aware of what version AS3 is installed on BIG-IQ before attempting to use

  vars: # Import CSV File
    csvfile: "{{ lookup('file', '../../variables/device_variables.csv') }}"

  tasks:

    - name: Python Script to create Vars list
      ansible.builtin.script:
        cmd: ../../scripts/vars_parse.py
        executable: /usr/bin/python3
      register: python_result

    - name: Include YAML style Vars from Python Output
      ansible.builtin.set_fact:
        devices: "{{ python_result.stdout }}"

    - name: BIG-IP Only create AS3 payload json based on Jinja2 Template and YAML from CSV # noqa: no-relative-paths
      ansible.builtin.template:
        src: "../../templates/as3_bigiq_json_template.j2"
        dest: "../../output/as3.{{ item.unit.hostname }}.json"
        # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
        mode: "0644"
      delegate_to: localhost
      with_items: "{{ devices }}"
      when: "'bigip' in item.unit.role"
