---
- name: Satic File based Full DO based on Hostname
  hosts: bigip
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: false

    - name: "ansible_password"
      prompt: "What is your password? "
      private: true

  vars: # Import Auth JSON
    f5_login_json: "{{ lookup('template', '../../templates/f5_web_auth.j2') }}"

  tasks:

    - name: Login and Obtain Token
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/authn/login"
        method: POST
        body: "{{ f5_login_json }}"
        body_format: json
        status_code:
          - 200
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: f5_login_token_post

    - name: Test Service Get
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/info"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        status_code:
          - 200
          - 202
        timeout: 300
        validate_certs: false
      delegate_to: localhost

    - name: BIG-IP Only PUSH DO Static File
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding"
        method: POST
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        body: "{{ lookup('file', '../../static_output/do.bigiq.{{ inventory_hostname }}.json') }}"
        status_code:
          - 200
          - 202
        timeout: 300
        body_format: json
        validate_certs: false
      delegate_to: localhost
