---
- name: TEST REST Auth Token (used for AS3 , DO, TS, etc.)
  hosts:
    - bigip
    - bigiq
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: false

    - name: "ansible_password"
      prompt: "What is your password? "
      private: true

  vars: # Create Auth JSON
    f5_login_json: "{{ lookup('template', '../../templates/f5_web_auth.j2') }}"

  tasks:

    - name: Login and Obtain Token
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/authn/login"
        method: POST
        body: "{{ f5_login_json }}"
        body_format: json
        status_code:
          - 200
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: f5_login_token_post

    - name: Display f5_login_token_post
      ansible.builtin.debug:
        msg: "{{ f5_login_token_post.json.token }}"
