---
- name: TEST Service Status with Auth Token (AS3 , DO)
  hosts:
    - bigip
    - bigiq
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ansible_user"
      prompt: "What is your username? "
      private: false

    - name: "ansible_password"
      prompt: "What is your password? "
      private: true

  vars: # Create Auth JSON
    f5_login_json: "{{ lookup('template', '../../templates/f5_web_auth.j2') }}"

  tasks:

    - name: Login and Obtain Token
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/authn/login"
        method: POST
        body: "{{ f5_login_json }}"
        body_format: json
        status_code:
          - 200
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        # When Possible Validate Certs - For testing may chose not to
        # validate_certs: false
      delegate_to: localhost
      register: f5_login_token_post

    - name: Display f5_login_token_post
      ansible.builtin.debug:
        msg: "{{ f5_login_token_post.json.token }}"

    - name: Test DO Service Get
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/declarative-onboarding/info"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        status_code:
          - 200
          - 202
        timeout: 300
        # When Possible Validate Certs - For testing may chose not to
        # validate_certs: false
      delegate_to: localhost
      register: f5_do_service
      tags:
        - service

    - name: "DISPLAY DO Result"
      ansible.builtin.debug:
        var: f5_do_service.json.results

    - name: "DISPLAY DO Errors if Any"
      ansible.builtin.debug:
        var: f5_do_service.json.errors

    - name: Test AS3 Service Get
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared/appsvcs/info"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_login_token_post.json.token.token }}"
        status_code:
          - 200
          - 202
        timeout: 300
        # When Possible Validate Certs - For testing may chose not to
        # validate_certs: false
      delegate_to: localhost
      register: f5_as3_service
      tags:
        - service

    - name: "DISPLAY AS3 Result"
      ansible.builtin.debug:
        var: f5_as3_service.json.results

    - name: "DISPLAY AS3 Errors if Any"
      ansible.builtin.debug:
        var: f5_as3_service.json.errors
