$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("X-F5-Auth-Token", "$responseToken")
$headers.Add("Content-Type", "application/json")

$body = @"
{
    `"`$schema`": `"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/main/schema/latest/as3-schema.json`",
    `"class`": `"AS3`",
    `"controls`": {
        `"trace`": true
    },
    `"declaration`": {
        `"class`": `"ADC`",
        `"schemaVersion`": `"3.41.0`",
        `"id`": `"urn:uuid:7e3971ab-0659-491b-8641-848f5349bc1b`",
        `"label`": `"Custom Generated Declaration`",
        `"remark`": `"Auto-generated by Ansible`",
        `"Tenant`": { }
    }
}
"@

$response = Invoke-RestMethod "https://$f5Hostname`:443/mgmt/shared/appsvcs/declare?async=true" -Method 'POST' -Headers $headers -Body $body
# $response | ConvertTo-Json
$responseDeclarationID = $response.id
$responseDeclarationID | ConvertTo-Json
